Algoritmo "primeiro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/07/2026
Var
// Seção de Declarações das variáveis 


Inicio
Escreval("Olá, Mundo")
Escreval("Me livrei da Maldição")
Escreval("Etapa, por etapa, irei evoluindo. Hoje é dia 21 de Julho de 2026, são 19h 13")
Fimalgoritmo
